// ---------------------------------------------------------------------------- 
//  Copyright (C) Synthara. All rights reserved.
//  Developed at Synthara, Zurich, Switzerland
//  All rights reserved. Reproduction in whole or part is prohibited without
//  the written permission of the copyright owner.
// ---------------------------------------------------------------------------- 

// WARNING: This package has been autogenerated highly not recommended to modify by hand 


package rvv_autogen_enums_pkg;
    // start import list
  
    import rvv_autogen_specs_pkg::*;
    import rvv_autogen_params_pkg::*;
    // end import list

    // start of package content
    typedef enum logic[OPERATOR_NUM_BIT - 1:0] {
        ALU_ABS = 5'd0,
        ALU_SLE = 5'd1,
        ALU_MIN = 5'd2,
        ALU_MAX = 5'd3,
        ALU_EXTHS = 5'd4,
        ALU_EXTHZ = 5'd5,
        ALU_EXTBS = 5'd6,
        ALU_EXTBZ = 5'd7,
        ALU_CLIP = 5'd8,
        ALU_CLIPU = 5'd9,
        ALU_ADD = 5'd10,
        ALU_ADDR = 5'd11,
        ALU_SUB = 5'd12,
        ALU_SUBR = 5'd13,
        ALU_SRL = 5'd14,
        ALU_SRA = 5'd15,
        ALU_SLL = 5'd16,
        ALU_OR = 5'd17,
        ALU_XOR = 5'd18,
        ALU_AND = 5'd19,
        MUL_DOT = 5'd20,
        ALU_EQ = 5'd21,
        ALU_NE = 5'd22,
        ALU_GT = 5'd23,
        ALU_GE = 5'd24,
        ALU_LT = 5'd25,
        ALU_LE = 5'd26,
        ALU_MUL = 5'd27,
        ALU_MULR = 5'd28,
        MAC_WORD_WIDTH = 5'd29,
        MSU_WORD_WIDTH = 5'd30
    } operator_dtype;
    
    typedef enum logic[OP_A_MUX_SEL_NUM_BIT - 1:0] {
        OP_A_MUX_SEL_OP_A = 1'd0,
        OP_A_MUX_SEL_OP_C = 1'd1
    } op_a_mux_sel_dtype;
    
    typedef enum logic[OP_B_MUX_SEL_NUM_BIT - 1:0] {
        OP_B_MUX_SEL_OP_B = 3'd0,
        OP_B_MUX_SEL_OP_B_SIMD = 3'd1,
        OP_B_MUX_CLIP_SEL_IMM = 3'd2,
        OP_B_MUX_CLIP_SEL_OP_B = 3'd3,
        OP_B_MUX_SEL_OP_A = 3'd4
    } op_b_mux_sel_dtype;
    
    typedef enum logic[OP_C_MUX_SEL_NUM_BIT - 1:0] {
        OP_C_MUX_SEL_ZERO = 1'd0,
        OP_C_MUX_SEL_OP_C = 1'd1
    } op_c_mux_sel_dtype;
    
    typedef enum logic {
        UNSIGNED = 0,
        SIGNED = 1
    } sign_mode_dtype;
    
    typedef enum logic[RN_VALUE_MUX_SEL_NUM_BIT - 1:0] {
        RN_VALUE_MUX_SEL_FROM_IMM = 2'd0,
        RN_VALUE_MUX_SEL_FROM_OP_B = 2'd1,
        RN_VALUE_MUX_SEL_ONE = 2'd2,
        RN_VALUE_MUX_SEL_ZERO = 2'd3
    } rn_value_mux_sel_dtype;
    
    typedef enum logic[VEC_MODE_NUM_BIT - 1:0] {
        W_MODE = 2'd0,
        B_MODE = 2'd1,
        H_MODE = 2'd2,
        MX_MODE = 2'd3
    } vec_mode_dtype;
    
    typedef enum logic[OP_B_MODE_NUM_BIT - 1:0] {
        NORM_MODE = 2'd0,
        SC_MODE = 2'd1,
        SCI_MODE = 2'd2
    } op_b_mode_dtype;
    
    typedef enum logic {
        IMM_UNSIGNED = 0,
        IMM_SIGNED = 1
    } sci_imm_sign_mode_dtype;
    
    typedef enum logic {
        LEFT = 1'd0,
        RIGHT = 1'd1
    } sh_mode_dtype;
    
    typedef enum logic {
        LOWER = 1'd0,
        UPPER = 1'd1
    } bit_sel_dtype;
    
    typedef enum logic[DOT_OPERAND_SIGN_MODE_NUM_BIT - 1:0] {
        UNSIGNED_UNSIGNED = 0,
        UNSIGNED_SIGNED = 2,
        SIGNED_UNSIGNED = 1,
        SIGNED_SIGNED = 3
    } dot_sign_mode_dtype;
    
    typedef enum logic[XLEN - 1:0] {
        INT4 = 0,
        INT8 = 1,
        INT16 = 2,
        INT32 = 3,
        INT8X4 = 4,
        INT16X4 = 5,
        INT16X8 = 6,
        INT32X16 = 7
    } data_csr_dtype;
    
    // end of package content
endpackage