// ---------------------------------------------------------------------------- 
//  Copyright (C) Synthara. All rights reserved.
//  Developed at Synthara, Zurich, Switzerland
//  All rights reserved. Reproduction in whole or part is prohibited without
//  the written permission of the copyright owner.
// ---------------------------------------------------------------------------- 

// WARNING: This package has been autogenerated highly not recommended to modify by hand 


package rvv_autogen_dtypes_pkg;
    // start import list
    import rvv_autogen_specs_pkg::*;
    import rvv_autogen_params_pkg::*;
    import rvv_autogen_enums_pkg::*;
    // end import list

    // start of package content
    typedef logic[INSTR_NUM_BIT - 1:0] instr_dtype;
    typedef logic[INSTR_COMPRESSED_NUM_BIT - 1:0] instr_compressed_dtype;
    typedef logic[ADDR_NUM_BIT - 1:0] reg_file_addr_dtype;
    typedef logic[READ_REG_FLAGS_LENGTH - 1:0] readregflags_t_dtype;
    typedef logic[X_DUALWRITE+1 - 1:0] writeregflags_t_dtype;
    typedef logic[X_ID_WIDTH - 1:0] id_t_dtype;
    typedef logic[X_HARTID_WIDTH - 1:0] hartid_t_dtype;
    typedef logic[X_NUM_RS - 1:0][X_RFR_WIDTH - 1:0] cv_x_packed_operand_dtype;
    typedef logic[X_RFR_WIDTH - 1:0] cv_x_operand_dtype;
    typedef logic[X_RFW_WIDTH - 1:0] cv_x_result_dtype;
    // end of package content
endpackage