`ifdef BASE
    // ---------------------------------------------------------------------------- 
    //  Copyright (C) Synthara. All rights reserved.
    //  Developed at Synthara, Zurich, Switzerland
    //  All rights reserved. Reproduction in whole or part is prohibited without
    //  the written permission of the copyright owner.
    // ---------------------------------------------------------------------------- 
    
    // WARNING: This package has been autogenerated highly not recommended to modify by hand 

    
    package rvv_autogen_specs_pkg;
        // start import list
    
        // end import list
    
        // start of package content
        localparam int unsigned  INSTR_NUM_BIT = 32;
        localparam int unsigned  OPCODE_MSB = 6;
        localparam int unsigned  OPCODE_LSB = 0;
        localparam int unsigned  OPCODE_NUM_BIT = 7;
        localparam int unsigned  FUNCT7_MSB = 31;
        localparam int unsigned  FUNCT7_LSB = 25;
        localparam int unsigned  FUNCT7_NUM_BIT = 7;
        localparam int unsigned  FUNCT5_MSB = 31;
        localparam int unsigned  FUNCT5_LSB = 27;
        localparam int unsigned  FUNCT5_NUM_BIT = 5;
        localparam int unsigned  FUNCT3_MSB = 14;
        localparam int unsigned  FUNCT3_LSB = 12;
        localparam int unsigned  FUNCT3_NUM_BIT = 3;
        localparam int unsigned  F2_MSB = 31;
        localparam int unsigned  F2_LSB = 30;
        localparam int unsigned  F2_NUM_BIT = 2;
        localparam int unsigned  F_FIELD = 26;
        localparam int unsigned  RD_ADDR_MSB = 11;
        localparam int unsigned  RD_ADDR_LSB = 7;
        localparam int unsigned  SCI_IMM_MSB = 25;
        localparam int unsigned  SCI_IMM_LSB = 20;
        localparam int unsigned  SCI_IMM_NUM_BIT = 6;
        localparam int unsigned  RN_IMM_MSB_FIRST_SET = 24;
        localparam int unsigned  RN_IMM_LSB_FIRST_SET = 20;
        localparam int unsigned  RN_IMM_MSB_SECOND_SET = 29;
        localparam int unsigned  RN_IMM_LSB_SECOND_SET = 25;
        localparam int unsigned  CLIP_IMM_MSB = 24;
        localparam int unsigned  CLIP_IMM_LSB = 20;
        localparam int unsigned  ALU_OPCODE_FIRST_SET = 43;
        localparam int unsigned  ALU_ABS_ENC = 40;
        localparam int unsigned  ALU_SLE_ENC = 41;
        localparam int unsigned  ALU_SLEU_ENC = 42;
        localparam int unsigned  ALU_MIN_ENC = 43;
        localparam int unsigned  ALU_MINU_ENC = 44;
        localparam int unsigned  ALU_MAX_ENC = 45;
        localparam int unsigned  ALU_MAXU_ENC = 46;
        localparam int unsigned  ALU_EXTHS_ENC = 48;
        localparam int unsigned  ALU_EXTHZ_ENC = 49;
        localparam int unsigned  ALU_EXTBS_ENC = 50;
        localparam int unsigned  ALU_EXTBZ_ENC = 51;
        localparam int unsigned  ALU_CLIP_ENC = 56;
        localparam int unsigned  ALU_CLIPU_ENC = 57;
        localparam int unsigned  ALU_CLIPR_ENC = 58;
        localparam int unsigned  ALU_CLIPUR_ENC = 59;
        localparam int unsigned  ALU_ADD_N_R_ENC = 64;
        localparam int unsigned  ALU_ADDU_N_R_ENC = 65;
        localparam int unsigned  ALU_ADD_RN_R_ENC = 66;
        localparam int unsigned  ALU_ADDU_RN_R_ENC = 67;
        localparam int unsigned  ALU_SUB_N_R_ENC = 68;
        localparam int unsigned  ALU_SUBU_N_R_ENC = 69;
        localparam int unsigned  ALU_SUB_RN_R_ENC = 70;
        localparam int unsigned  ALU_SUBU_RN_R_ENC = 71;
        localparam int unsigned  ALU_OPCODE_SECOND_SET = 91;
        localparam int unsigned  ALU_ADD_N_ENC = 2;
        localparam int unsigned  ALU_ADDU_N_ENC = 10;
        localparam int unsigned  ALU_ADD_RN_ENC = 18;
        localparam int unsigned  ALU_ADDU_RN_ENC = 26;
        localparam int unsigned  ALU_SUB_N_ENC = 3;
        localparam int unsigned  ALU_SUBU_N_ENC = 11;
        localparam int unsigned  ALU_SUB_RN_ENC = 19;
        localparam int unsigned  ALU_SUBU_RN_ENC = 27;
        localparam int unsigned  SIMD_OPCODE = 123;
        localparam int unsigned  SIMD_ADD_ENC = 0;
        localparam int unsigned  SIMD_SUB_ENC = 2;
        localparam int unsigned  SIMD_AVG_ENC = 4;
        localparam int unsigned  SIMD_AVGU_ENC = 6;
        localparam int unsigned  SIMD_MIN_ENC = 8;
        localparam int unsigned  SIMD_MINU_ENC = 10;
        localparam int unsigned  SIMD_MAX_ENC = 12;
        localparam int unsigned  SIMD_MAXU_ENC = 14;
        localparam int unsigned  SIMD_SRL_ENC = 16;
        localparam int unsigned  SIMD_SRA_ENC = 18;
        localparam int unsigned  SIMD_SLL_ENC = 20;
        localparam int unsigned  SIMD_OR_ENC = 22;
        localparam int unsigned  SIMD_XOR_ENC = 24;
        localparam int unsigned  SIMD_AND_ENC = 26;
        localparam int unsigned  SIMD_ABS_ENC = 28;
        localparam int unsigned  SIMD_DOTUP_ENC = 32;
        localparam int unsigned  SIMD_DOTUSP_ENC = 34;
        localparam int unsigned  SIMD_DOTSP_ENC = 36;
        localparam int unsigned  SIMD_SDOTUP_ENC = 38;
        localparam int unsigned  SIMD_SDOTUSP_ENC = 40;
        localparam int unsigned  SIMD_SDOTSP_ENC = 42;
        localparam int unsigned  SIMD_CMPEQ = 1;
        localparam int unsigned  SIMD_CMPNE = 3;
        localparam int unsigned  SIMD_CMPGT = 5;
        localparam int unsigned  SIMD_CMPGE = 7;
        localparam int unsigned  SIMD_CMPLT = 9;
        localparam int unsigned  SIMD_CMPLE = 11;
        localparam int unsigned  SIMD_CMPGTU = 13;
        localparam int unsigned  SIMD_CMPGEU = 15;
        localparam int unsigned  SIMD_CMPLTU = 17;
        localparam int unsigned  SIMD_CMPLEU = 19;
        localparam int unsigned  NORM_MODE_ENC = 0;
        localparam int unsigned  SC_MODE_ENC = 4;
        localparam int unsigned  SCI_MODE_ENC = 6;
        localparam int unsigned  NUM_OP_B_MODE = 3;
        localparam int unsigned  NUM_DOT_SIGN_MODE = 3;
        localparam int unsigned  LOWER_ENC = 0;
        localparam int unsigned  UPPER_ENC = 1;
        localparam int unsigned  LOWER_ROUND_ENC = 2;
        localparam int unsigned  UPPER_ROUND_ENC = 3;
        localparam int unsigned  MUL_SIGNED_ENC = 0;
        localparam int unsigned  MUL_UNSIGNED_ENC = 1;
        localparam int unsigned  MAC_SIGNED_ENC = 2;
        localparam int unsigned  MAC_UNSIGNED_ENC = 3;
        localparam int unsigned  MAC_WORD_WIDTH_ENC = 72;
        localparam int unsigned  MSU_WORD_WIDTH_ENC = 73;
        localparam int unsigned  X_NUM_RS = 3;
        localparam int unsigned  X_ID_WIDTH = 4;
        localparam int unsigned  X_RFR_WIDTH = 32;
        localparam int unsigned  X_RFW_WIDTH = 32;
        localparam int unsigned  X_NUM_HARTS = 1;
        localparam int unsigned  X_HARTID_WIDTH = 1;
        localparam int unsigned  X_MISA = 0;
        localparam int unsigned  X_DUALREAD = 0;
        localparam int unsigned  X_DUALWRITE = 0;
        localparam int unsigned  X_ISSUE_REGISTER_SPLIT = 0;
        localparam int unsigned  XLEN = 32;
        localparam int unsigned  WORD_NUM_BIT = 32;
        localparam int unsigned  NUM_OPERATOR = 31;
        localparam int unsigned  NUM_OP_A_VALUE = 2;
        localparam int unsigned  NUM_OP_B_VALUE = 5;
        localparam int unsigned  NUM_OP_C_VALUE = 2;
        localparam int unsigned  NUM_RN_VALUE = 4;
        localparam int unsigned  NUM_VEC_MODE = 3;
        // end of package content
    endpackage

`else
    $stop("VERSION MISSING: You need to specify one version of XCS.") 
`endif