`ifdef BASE
    // ---------------------------------------------------------------------------- 
    //  Copyright (C) Synthara. All rights reserved.
    //  Developed at Synthara, Zurich, Switzerland
    //  All rights reserved. Reproduction in whole or part is prohibited without
    //  the written permission of the copyright owner.
    // ---------------------------------------------------------------------------- 
    
    // WARNING: This package has been autogenerated highly not recommended to modify by hand 
    
    
    package rvv_autogen_params_pkg;
        // start import list
        import rvv_autogen_specs_pkg::*;
        // end import list
    
        // start of package content
        // INSTR_COMPRESSED_NUM_BIT = INSTR_NUM_BIT/2;
        localparam int unsigned INSTR_COMPRESSED_NUM_BIT = 16;
        // BYTE_NUM_BIT = WORD_NUM_BIT/4;
        localparam int unsigned BYTE_NUM_BIT = 8;
        // HALF_WORD_NUM_BIT = WORD_NUM_BIT/2;
        localparam int unsigned HALF_WORD_NUM_BIT = 16;
        // HALF_WORD_NUM_BYTE = HALF_WORD_NUM_BIT/BYTE_NUM_BIT;
        localparam int unsigned HALF_WORD_NUM_BYTE = 2;
        // BYTE_PER_WORD = WORD_NUM_BIT/BYTE_NUM_BIT;
        localparam int unsigned BYTE_PER_WORD = 4;
        // HALF_WORD_PER_WORD = WORD_NUM_BIT/HALF_WORD_NUM_BIT;
        localparam int unsigned HALF_WORD_PER_WORD = 2;
        // BYTE_SH_AMT_NUM_BIT = $clog2(BYTE_NUM_BIT);
        localparam int unsigned BYTE_SH_AMT_NUM_BIT = 3;
        // HALF_WORD_SH_AMT_NUM_BIT = $clog2(HALF_WORD_NUM_BIT);
        localparam int unsigned HALF_WORD_SH_AMT_NUM_BIT = 4;
        // ADDR_NUM_BIT = $clog2(INSTR_NUM_BIT);
        localparam int unsigned ADDR_NUM_BIT = 5;
        // WORD_SH_AMT_NUM_BIT = $clog2(WORD_NUM_BIT);
        localparam int unsigned WORD_SH_AMT_NUM_BIT = 5;
        // OPERATOR_NUM_BIT = $clog2(NUM_OPERATOR);
        localparam int unsigned OPERATOR_NUM_BIT = 5;
        // OP_A_MUX_SEL_NUM_BIT = $clog2(NUM_OP_A_VALUE);
        localparam int unsigned OP_A_MUX_SEL_NUM_BIT = 1;
        // OP_B_MUX_SEL_NUM_BIT = $clog2(NUM_OP_B_VALUE);
        localparam int unsigned OP_B_MUX_SEL_NUM_BIT = 3;
        // OP_C_MUX_SEL_NUM_BIT = $clog2(NUM_OP_C_VALUE);
        localparam int unsigned OP_C_MUX_SEL_NUM_BIT = 1;
        // RN_VALUE_MUX_SEL_NUM_BIT = $clog2(NUM_RN_VALUE);
        localparam int unsigned RN_VALUE_MUX_SEL_NUM_BIT = 2;
        // VEC_MODE_NUM_BIT = $clog2(NUM_VEC_MODE);
        localparam int unsigned VEC_MODE_NUM_BIT = 2;
        // OP_B_MODE_NUM_BIT = $clog2(NUM_OP_B_MODE);
        localparam int unsigned OP_B_MODE_NUM_BIT = 2;
        // DOT_OPERAND_SIGN_MODE_NUM_BIT = $clog2(NUM_DOT_SIGN_MODE);
        localparam int unsigned DOT_OPERAND_SIGN_MODE_NUM_BIT = 2;
        // READ_REG_FLAGS_LENGTH = X_NUM_RS+X_DUALREAD;
        localparam int unsigned READ_REG_FLAGS_LENGTH = 3;
        // end of package content
    endpackage

`else
    $stop("VERSION MISSING: You need to specify one version of XCS.") 
`endif