// ---------------------------------------------------------------------------- 
//  Copyright (C) Synthara. All rights reserved.
//  Developed at Synthara, Zurich, Switzerland
//  All rights reserved. Reproduction in whole or part is prohibited without
//  the written permission of the copyright owner.
// ---------------------------------------------------------------------------- 

// WARNING: This package has been autogenerated highly not recommended to modify by hand 

package rvv_autogen_structs_pkg;
    // start import list
    import rvv_autogen_specs_pkg::*;
    import rvv_autogen_params_pkg::*;
    import rvv_autogen_enums_pkg::*;
    import rvv_autogen_dtypes_pkg::*;
    // end import list

    // start of package content
    typedef struct packed {
        instr_compressed_dtype instr;
        hartid_t_dtype hartid;
    } x_compressed_req_t_dtype;
    
    typedef struct packed {
        instr_dtype instr;
        logic accept;
    } x_compressed_resp_t_dtype;
    
    typedef struct packed {
        instr_dtype instr;
        hartid_t_dtype hartid;
        id_t_dtype id;
    } x_issue_req_t_dtype;
    
    typedef struct packed {
        logic accept;
        writeregflags_t_dtype writeback;
        readregflags_t_dtype register_read;
    } x_issue_resp_t_dtype;
    
    typedef struct packed {
        hartid_t_dtype hartid;
        id_t_dtype id;
        cv_x_packed_operand_dtype rs;
        readregflags_t_dtype rs_valid;
    } x_register_t_dtype;
    
    typedef struct packed {
        hartid_t_dtype hartid;
        id_t_dtype id;
        logic commit_kill;
    } x_commit_t_dtype;
    
    typedef struct packed {
        hartid_t_dtype hartid;
        id_t_dtype id;
        cv_x_result_dtype data;
        reg_file_addr_dtype rd;
        writeregflags_t_dtype we;
    } x_result_t_dtype;
    
    typedef struct packed {
        logic instr_valid;
        operator_dtype operator;
        op_a_mux_sel_dtype op_a_mux_sel;
        op_b_mux_sel_dtype op_b_mux_sel;
        op_c_mux_sel_dtype op_c_mux_sel;
        sign_mode_dtype sign_mode;
        rn_value_mux_sel_dtype rn_value_mux_sel;
        vec_mode_dtype vec_mode;
        op_b_mode_dtype op_b_mode;
        sci_imm_sign_mode_dtype sci_imm_sign_mode;
        sh_mode_dtype sh_mode;
        dot_sign_mode_dtype dot_sign_mode;
        bit_sel_dtype bit_sel;
        reg_file_addr_dtype rd_addr;
        logic alu_en;
        logic mul_en;
        logic[SCI_IMM_NUM_BIT - 1:0] sci_imm;
        logic[WORD_SH_AMT_NUM_BIT - 1:0] rn_imm;
        logic[WORD_SH_AMT_NUM_BIT - 1:0] clip_imm;
    } dec_ctrl_dtype;
    
    typedef struct packed {
        operator_dtype operator;
        sign_mode_dtype sign_mode;
        vec_mode_dtype vec_mode;
        sh_mode_dtype sh_mode;
    } alu_ctrl_dtype;
    
    typedef struct packed {
        operator_dtype operator;
        sign_mode_dtype sign_mode;
        vec_mode_dtype vec_mode;
        dot_sign_mode_dtype dot_sign_mode;
        bit_sel_dtype bit_sel;
        logic[WORD_SH_AMT_NUM_BIT - 1:0] rn_imm;
    } mul_ctrl_dtype;
    

    
    // end of package content
endpackage